CREATE DATABASE dbo;
GO

-- SCRIPT GERAÇÃO DAS TABELAS "COMUNS"
CREATE TABLE [dbo].[conta_contasref]
(
    [ctaref_idseq]              [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](130)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [ind_ref]                   [char](1)               NULL,
    [cod_cta]                   [varchar](60)           NULL,
    [cod_ccus]                  [varchar](60)           NULL,
    [perc_rateio]               [numeric](9, 4)         NULL,
    [cod_cta_ref]               [varchar](60)           NULL,
    [validade_dtini]            [varchar](8)            NULL,
    [validade_dtfin]            [varchar](8)            NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[contabilistas]
(
    [contabilista_idseq]        [bigint] IDENTITY (1,1) NOT NULL,
    [estabelecimento_idseq]     [bigint]                NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [contabilista_id]           [varchar](60)           NULL,
    [cpf]                       [varchar](11)           NULL,
    [cnpj]                      [varchar](14)           NULL,
    [crc]                       [varchar](15)           NULL,
    [uf_crc]                    [varchar](2)            NULL,
    [num_seq_crc]               [varchar](60)           NULL,
    [dt_crc]                    [varchar](8)            NULL,
    [nome]                      [varchar](100)          NULL,
    [fantasia]                  [varchar](60)           NULL,
    [cep]                       [varchar](8)            NULL,
    [ender]                     [varchar](60)           NULL,
    [num]                       [varchar](60)           NULL,
    [compl]                     [varchar](60)           NULL,
    [bairro]                    [varchar](60)           NULL,
    [fone]                      [varchar](11)           NULL,
    [fax]                       [varchar](11)           NULL,
    [email]                     [varchar](2000)         NULL,
    [cod_mun]                   [varchar](7)            NULL,
    [uf]                        [varchar](2)            NULL,
    [cod_pais]                  [varchar](5)            NULL,
    [validade_dtini]            [varchar](8)            NULL,
    [validade_dtfin]            [varchar](8)            NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[contas]
(
    [conta_idseq]               [bigint] IDENTITY (1,1) NOT NULL,
    [estabelecimento_idseq]     [bigint]                NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [conta_id]                  [varchar](60)           NULL,
    [cod_cta]                   [varchar](60)           NULL,
    [nome_cta]                  [varchar](2000)         NULL,
    [cod_nat_cta]               [varchar](2)            NULL,
    [ind_cta]                   [varchar](1)            NULL,
    [nivel]                     [numeric](2, 0)         NULL,
    [cod_cta_sup]               [varchar](60)           NULL,
    [cod_cta_ref]               [varchar](60)           NULL,
    [inclusao_dt]               [varchar](8)            NULL,
    [validade_dtini]            [varchar](8)            NULL,
    [validade_dtfin]            [varchar](8)            NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[estabelecimento_ecf]
(
    [estecf_idseq]              [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [cod_scp]                   [varchar](14)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [nome_esc]                  [char](4)               NULL,
    [cod_ver]                   [char](4)               NULL,
    [ind_sit_ini_per]           [char](1)               NULL,
    [sit_especial]              [char](1)               NULL,
    [pat_reman_cis]             [numeric](9, 4)         NULL,
    [dt_sit_esp]                [varchar](8)            NULL,
    [retificadora]              [char](1)               NULL,
    [num_rec]                   [varchar](41)           NULL,
    [tip_ecf]                   [char](1)               NULL,
    [hash_ecf_anterior]         [varchar](40)           NULL,
    [opt_refis]                 [char](1)               NULL,
    [forma_trib]                [char](1)               NULL,
    [forma_apur]                [char](1)               NULL,
    [cod_qualif_pj]             [char](2)               NULL,
    [forma_trib_per]            [char](4)               NULL,
    [mes_bal_red]               [varchar](12)           NULL,
    [tip_esc_pre]               [char](1)               NULL,
    [tip_ent]                   [char](2)               NULL,
    [forma_apur_i]              [char](1)               NULL,
    [apur_csll]                 [char](1)               NULL,
    [ind_rec_receita]           [char](1)               NULL,
    [ind_aliq_csll]             [char](1)               NULL,
    [ind_qte_scp]               [numeric](3, 0)         NULL,
    [ind_adm_fun_clus]          [char](1)               NULL,
    [ind_part_cons]             [char](1)               NULL,
    [ind_op_ext]                [char](1)               NULL,
    [ind_op_vinc]               [char](1)               NULL,
    [ind_pj_enquad]             [char](1)               NULL,
    [ind_part_ext]              [char](1)               NULL,
    [ind_ativ_rural]            [char](1)               NULL,
    [ind_luc_exp]               [char](1)               NULL,
    [ind_red_isen]              [char](1)               NULL,
    [ind_fin]                   [char](1)               NULL,
    [ind_part_colig]            [char](1)               NULL,
    [ind_rec_ext]               [char](1)               NULL,
    [ind_ativ_ext]              [char](1)               NULL,
    [ind_pgto_ext]              [char](1)               NULL,
    [ind_e_com_ti]              [char](1)               NULL,
    [ind_roy_rec]               [char](1)               NULL,
    [ind_roy_pag]               [char](1)               NULL,
    [ind_rend_serv]             [char](1)               NULL,
    [ind_pgto_rem]              [char](1)               NULL,
    [ind_inov_tec]              [char](1)               NULL,
    [ind_cap_inf]               [char](1)               NULL,
    [ind_pj_hab]                [char](1)               NULL,
    [ind_polo_am]               [char](1)               NULL,
    [ind_zon_exp]               [char](1)               NULL,
    [ind_area_com]              [char](1)               NULL,
    [ind_pais_a_pais]           [char](1)               NULL,
    [ind_derex]                 [char](1)               NULL,
    [ind_aval_estoq]            [char](1)               NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[estabelecimento_signatarios]
(
    [estsig_idseq]              [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [ident_cpf_cnpj]            [varchar](14)           NULL,
    [ident_nom]                 [varchar](2000)         NULL,
    [cod_assin]                 [char](3)               NULL,
    [email]                     [varchar](60)           NULL,
    [fone]                      [varchar](20)           NULL,
    [ind_resp_legal]            [char](1)               NULL,
    [validade_dtini]            [varchar](8)            NULL,
    [validade_dtfin]            [varchar](8)            NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL,
    [ident_qualif]              [varchar](120)          NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[estabelecimentos]
(
    [estabelecimento_id]        [varchar](60)           NULL,
    [cnpj]                      [varchar](60)           NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [estabelecimento_id_ant]    [varchar](60)           NULL,
    [nome]                      [varchar](100)          NULL,
    [fantasia]                  [varchar](60)           NULL,
    [cep]                       [varchar](8)            NULL,
    [ender]                     [varchar](60)           NULL,
    [num]                       [varchar](60)           NULL,
    [compl]                     [varchar](60)           NULL,
    [bairro]                    [varchar](60)           NULL,
    [fone]                      [varchar](11)           NULL,
    [fax]                       [varchar](11)           NULL,
    [email]                     [varchar](2000)         NULL,
    [cod_mun]                   [varchar](7)            NULL,
    [uf]                        [varchar](2)            NULL,
    [cod_pais]                  [varchar](5)            NULL,
    [ie]                        [varchar](14)           NULL,
    [im]                        [varchar](60)           NULL,
    [suframa]                   [varchar](9)            NULL,
    [nit]                       [varchar](11)           NULL,
    [ind_nat_pj]                [varchar](2)            NULL,
    [ind_ativ]                  [varchar](1)            NULL,
    [clas_estab_ind]            [varchar](2)            NULL,
    [validade_dtini]            [varchar](8)            NULL,
    [validade_dtfin]            [varchar](8)            NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [estabelecimento_idseq]     [bigint]                NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL,
    [est_idseq]                 [bigint] IDENTITY (1,1) NOT NULL,
    [apelido]                   [varchar](30)           NULL,
    [nire]                      [varchar](11)           NULL,
    [dt_arq_atos]               [varchar](8)            NULL,
    [dt_conv_ss_se]             [varchar](8)            NULL,
    [cod_nat_jur]               [char](4)               NULL,
    [cnae_fiscal]               [char](7)               NULL,
    [id_emp_dfe]                [int]                   NULL,
    [id_emp_erp]                [varchar](60)           NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[participantes]
(
    [reg]                       [varchar](100)          NULL,
    [part_idseq]                [bigint] IDENTITY (1,1) NOT NULL,
    [estabelecimento_idseq]     [bigint]                NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [participante_id]           [varchar](60)           NULL,
    [pessoa_id]                 [varchar](60)           NULL,
    [pessoa_tipo]               [varchar](1)            NULL,
    [nome]                      [varchar](100)          NULL,
    [fantasia]                  [varchar](60)           NULL,
    [cep]                       [varchar](8)            NULL,
    [ender]                     [varchar](120)          NULL,
    [num]                       [varchar](60)           NULL,
    [compl]                     [varchar](60)           NULL,
    [bairro]                    [varchar](60)           NULL,
    [fone]                      [varchar](11)           NULL,
    [fax]                       [varchar](11)           NULL,
    [email]                     [varchar](2000)         NULL,
    [cod_mun]                   [varchar](7)            NULL,
    [uf]                        [varchar](2)            NULL,
    [cod_pais]                  [varchar](5)            NULL,
    [cnpj]                      [varchar](14)           NULL,
    [cpf]                       [varchar](11)           NULL,
    [ie]                        [varchar](14)           NULL,
    [im]                        [varchar](60)           NULL,
    [suframa]                   [varchar](9)            NULL,
    [nit]                       [varchar](11)           NULL,
    [validade_dtini]            [varchar](8)            NULL,
    [validade_dtfin]            [varchar](8)            NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [cpf_produtor]              [varchar](11)           NULL,
    [ind_cprb]                  [varchar](1)            NULL,
    [per_ref]                   [varchar](8)            NULL,
    [ie_ant]                    [varchar](14)           NULL,
    [cod_spdipam]               [varchar](2)            NULL,
    [reg_uid]                   [varchar](44)           NULL,
    [cod_part]                  [varchar](60)           NULL,
    [forma_trib_fem]            [varchar](3)            NULL
) ON [PRIMARY]
GO


-- SCRIPT GERAÇÃO DAS TABELAS ECF
CREATE TABLE [dbo].[ecf_bcincentivos]
(
    [ecfbcinc_idseq]            [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [base_calc]                 [numeric](19, 2)        NULL,
    [per_incen_finor]           [numeric](9, 4)         NULL,
    [vl_liq_incen_finor]        [numeric](19, 2)        NULL,
    [per_incen_finam]           [numeric](9, 4)         NULL,
    [vl_liq_incen_finam]        [numeric](19, 2)        NULL,
    [vl_total]                  [numeric](19, 2)        NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_declpais]
(
    [ecfdpais_idseq]            [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [nome_multinacional]        [varchar](2000)         NULL,
    [ind_controladora]          [char](1)               NULL,
    [nome_controladora]         [varchar](2000)         NULL,
    [jurisdicao_controladora]   [char](2)               NULL,
    [tin_controladora]          [varchar](2000)         NULL,
    [ind_entrega]               [char](1)               NULL,
    [ind_modalidade]            [char](1)               NULL,
    [nome_substituta]           [varchar](2000)         NULL,
    [jurisdicao_substituta]     [char](2)               NULL,
    [tin_substituta]            [char](14)              NULL,
    [dtini_controladora]        [varchar](8)            NULL,
    [dtfin_controladora]        [varchar](8)            NULL,
    [tip_moeda]                 [char](3)               NULL,
    [ind_idioma]                [char](2)               NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_declpais_entidades]
(
    [ecfdpent_idseq]            [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [jurisdicao]                [char](2)               NULL,
    [jur_diferente]             [char](2)               NULL,
    [nome]                      [varchar](2000)         NULL,
    [tin]                       [varchar](2000)         NULL,
    [jurisdicao_tin]            [char](2)               NULL,
    [ni]                        [varchar](2000)         NULL,
    [jurisdicao_ni]             [char](2)               NULL,
    [tipo_ni]                   [varchar](2000)         NULL,
    [tip_end]                   [char](7)               NULL,
    [endereco]                  [varchar](150)          NULL,
    [num_tel]                   [varchar](15)           NULL,
    [email]                     [varchar](115)          NULL,
    [desc_outros]               [varchar](255)          NULL,
    [observacao]                [varchar](1000)         NULL,
    [ativ_01]                   [char](1)               NULL,
    [ativ_02]                   [char](1)               NULL,
    [ativ_03]                   [char](1)               NULL,
    [ativ_04]                   [char](1)               NULL,
    [ativ_05]                   [char](1)               NULL,
    [ativ_06]                   [char](1)               NULL,
    [ativ_07]                   [char](1)               NULL,
    [ativ_08]                   [char](1)               NULL,
    [ativ_09]                   [char](1)               NULL,
    [ativ_10]                   [char](1)               NULL,
    [ativ_11]                   [char](1)               NULL,
    [ativ_12]                   [char](1)               NULL,
    [ativ_13]                   [char](1)               NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_declpais_observacoes]
(
    [ecfdpobs_idseq]            [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [jurisdicao]                [varchar](2)            NULL,
    [ind_rec_nao_rel]           [char](1)               NULL,
    [ind_rec_rel]               [char](1)               NULL,
    [ind_rec_total]             [char](1)               NULL,
    [ind_luc_prej_antes_ir]     [char](1)               NULL,
    [ind_ir_pago]               [char](1)               NULL,
    [ind_ir_devido]             [char](1)               NULL,
    [ind_cap_soc]               [char](1)               NULL,
    [ind_luc_acum]              [char](1)               NULL,
    [ind_ativ_tang]             [char](1)               NULL,
    [ind_num_emp]               [char](1)               NULL,
    [observacao]                [varchar](4000)         NULL,
    [fim_observacao]            [char](7)               NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_declpais_valores]
(
    [ecfdpval_idseq]            [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [jurisdicao]                [char](2)               NULL,
    [vl_rec_nao_rel_est]        [numeric](19, 6)        NULL,
    [vl_rec_nao_rel]            [numeric](19, 6)        NULL,
    [vl_rec_rel_est]            [numeric](19, 6)        NULL,
    [vl_rec_rel]                [numeric](19, 6)        NULL,
    [vl_rec_total_est]          [numeric](19, 6)        NULL,
    [vl_rec_total]              [numeric](19, 6)        NULL,
    [vl_luc_prej_antes_ir_est]  [numeric](19, 6)        NULL,
    [vl_luc_prej_antes_ir]      [numeric](19, 6)        NULL,
    [vl_ir_pago_est]            [numeric](19, 6)        NULL,
    [vl_ir_pago]                [numeric](19, 6)        NULL,
    [vl_ir_devido_est]          [numeric](19, 6)        NULL,
    [vl_ir_devido]              [numeric](19, 6)        NULL,
    [vl_cap_soc_est]            [numeric](19, 6)        NULL,
    [vl_cap_soc]                [numeric](19, 6)        NULL,
    [vl_luc_acum_est]           [numeric](19, 6)        NULL,
    [vl_luc_acum]               [numeric](19, 6)        NULL,
    [vl_ativ_tang_est]          [numeric](19, 6)        NULL,
    [vl_ativ_tang]              [numeric](19, 6)        NULL,
    [num_emp]                   [numeric](7, 0)         NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_derex]
(
    [ecfderex_idseq]            [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [nome_instituicao]          [varchar](2000)         NULL,
    [pais]                      [char](2)               NULL,
    [tip_moeda]                 [varchar](2000)         NULL,
    [nome_resp]                 [varchar](2000)         NULL,
    [endereco_resp]             [varchar](2000)         NULL,
    [tipo_doc]                  [varchar](2000)         NULL,
    [ni_resp]                   [varchar](2000)         NULL,
    [ident_conta]               [varchar](2000)         NULL,
    [codigo_linha]              [varchar](2)            NULL,
    [descricao_linha]           [varchar](1000)         NULL,
    [valor_linha]               [numeric](19, 2)        NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_infoecon_ativinc]
(
    [ecfieai_idseq]             [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [ind_ativ]                  [char](2)               NULL,
    [ind_concedente]            [char](2)               NULL,
    [ind_proj]                  [char](2)               NULL,
    [ato_conc]                  [varchar](30)           NULL,
    [vig_ini]                   [varchar](8)            NULL,
    [vig_fim]                   [varchar](8)            NULL,
    [cnpj_incentivo]            [varchar](14)           NULL,
    [ncm_incentivo]             [varchar](8)            NULL,
    [rec_liq_incentivo]         [numeric](19, 2)        NULL,
    [vl_incentivo]              [numeric](19, 2)        NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_infoecon_comeletro]
(
    [ecfiecomel_idseq]          [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [pais]                      [varchar](3)            NULL,
    [ind_home_disp]             [char](1)               NULL,
    [ind_serv_disp]             [char](1)               NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_infoecon_expimp]
(
    [ecfieexpimp_idseq]         [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [ind_expimp]                [char](1)               NULL,
    [num_ordem]                 [numeric](7, 0)         NULL,
    [tip_expimp]                [char](2)               NULL,
    [desc_expimp]               [varchar](2000)         NULL,
    [tot_oper]                  [numeric](19, 2)        NULL,
    [cod_ncm]                   [char](8)               NULL,
    [qtde]                      [numeric](19, 6)        NULL,
    [uni_med]                   [char](2)               NULL,
    [tip_met]                   [varchar](5)            NULL,
    [ind_oper]                  [char](1)               NULL,
    [cod_inv]                   [varchar](60)           NULL,
    [util_ins_prod]             [char](2)               NULL,
    [oper_par]                  [char](1)               NULL,
    [desc_bens_par]             [varchar](2000)         NULL,
    [id_parte_par]              [varchar](2000)         NULL,
    [tip_par]                   [char](1)               NULL,
    [dt_util]                   [char](1)               NULL,
    [crit_par]                  [varchar](2000)         NULL,
    [dt_trans]                  [numeric](8, 0)         NULL,
    [dt_emb_duimp]              [numeric](8, 0)         NULL,
    [id_font_cot]               [numeric](3, 0)         NULL,
    [aj_par]                    [char](1)               NULL,
    [vl_par]                    [numeric](19, 2)        NULL,
    [vl_prat]                   [numeric](19, 2)        NULL,
    [qtde_aj]                   [numeric](19, 6)        NULL,
    [vl_aj]                     [numeric](19, 2)        NULL,
    [valor_cot]                 [numeric](19, 2)        NULL,
    [num_dec_expimp]            [varchar](50)           NULL,
    [dt_ent_prev]               [char](8)               NULL,
    [vl_jur]                    [numeric](19, 2)        NULL,
    [tx_jur_min]                [numeric](9, 4)         NULL,
    [tx_jur_max]                [numeric](9, 4)         NULL,
    [cod_cnc]                   [varchar](5)            NULL,
    [tip_moeda]                 [varchar](3)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_infoecon_expimp_ajustespp]
(
    [ecfieeiajpp_idseq]         [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](130)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [ind_expimp]                [char](1)               NULL,
    [num_ordem]                 [numeric](7, 0)         NULL,
    [tip_expimp]                [char](2)               NULL,
    [cod_ncm]                   [varchar](8)            NULL,
    [cod_inv]                   [varchar](60)           NULL,
    [tip_ajust]                 [varchar](2)            NULL,
    [desc_out_aj]               [varchar](2000)         NULL,
    [valor_aj]                  [numeric](19, 2)        NULL,
    [font_aj]                   [varchar](2000)         NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_infoecon_expimp_participantes]
(
    [ecfieeipart_idseq]         [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](130)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [ind_expimp]                [char](1)               NULL,
    [num_ordem]                 [numeric](7, 0)         NULL,
    [tip_oper]                  [char](2)               NULL,
    [cod_ncm]                   [varchar](8)            NULL,
    [cod_inv]                   [varchar](60)           NULL,
    [cod_part]                  [varchar](60)           NULL,
    [nome]                      [varchar](2000)         NULL,
    [pais]                      [varchar](2000)         NULL,
    [vl_oper]                   [numeric](19, 2)        NULL,
    [cond_pes]                  [varchar](2)            NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_infoecon_investidoras]
(
    [ecfieinvest_idseq]         [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](130)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [nif]                       [varchar](60)           NULL,
    [cnpj]                      [varchar](14)           NULL,
    [raz_social]                [varchar](2000)         NULL,
    [pais]                      [varchar](3)            NULL,
    [nif_cnpj]                  [varchar](60)           NULL,
    [razao_social]              [varchar](2000)         NULL,
    [perc_part]                 [numeric](9, 4)         NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_infoecon_participacoesext]
(
    [ecfieprtex_idseq]            [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                      [varchar](60)           NULL,
    [id]                          [varchar](130)          NULL,
    [estabelecimento_matriz_id]   [varchar](60)           NULL,
    [periodo_dtini]               [varchar](8)            NULL,
    [periodo_dtfin]               [varchar](8)            NULL,
    [nif]                         [varchar](60)           NULL,
    [cnpj]                        [varchar](14)           NULL,
    [raz_social]                  [varchar](2000)         NULL,
    [ind_controle]                [numeric](2, 0)         NULL,
    [pais]                        [varchar](3)            NULL,
    [ind_isen_petr]               [char](1)               NULL,
    [ind_consol]                  [char](1)               NULL,
    [mot_nao_consol]              [numeric](1, 0)         NULL,
    [tip_moeda]                   [char](3)               NULL,
    [rec_liq]                     [numeric](19, 2)        NULL,
    [custos]                      [numeric](19, 2)        NULL,
    [luc_bruto]                   [numeric](19, 2)        NULL,
    [rec_auferidas]               [numeric](19, 2)        NULL,
    [rec_outras_oper]             [numeric](19, 2)        NULL,
    [desp_brasil]                 [numeric](19, 2)        NULL,
    [desp_oper]                   [numeric](19, 2)        NULL,
    [luc_oper]                    [numeric](19, 2)        NULL,
    [rec_partic]                  [numeric](19, 2)        NULL,
    [rec_outras]                  [numeric](19, 2)        NULL,
    [desp_outras]                 [numeric](19, 2)        NULL,
    [luc_liq_ant_ir]              [numeric](19, 2)        NULL,
    [luc_arb_ant_ir]              [numeric](19, 2)        NULL,
    [imp_dev]                     [numeric](19, 2)        NULL,
    [luc_liq]                     [numeric](19, 2)        NULL,
    [res_inv_per]                 [numeric](19, 2)        NULL,
    [res_inv_per_real]            [numeric](19, 2)        NULL,
    [res_isen_petr_per]           [numeric](19, 2)        NULL,
    [res_isen_petr_per_real]      [numeric](19, 2)        NULL,
    [res_neg_acum]                [numeric](19, 2)        NULL,
    [res_pos_trib]                [numeric](19, 2)        NULL,
    [res_pos_trib_real]           [numeric](19, 2)        NULL,
    [imp_lucr]                    [numeric](19, 2)        NULL,
    [imp_lucr_real]               [numeric](19, 2)        NULL,
    [imp_pag_rend]                [numeric](19, 2)        NULL,
    [imp_pag_rend_real]           [numeric](19, 2)        NULL,
    [imp_ret_ext]                 [numeric](19, 2)        NULL,
    [imp_ret_ext_real]            [numeric](19, 2)        NULL,
    [imp_ret_br]                  [numeric](19, 2)        NULL,
    [res_per]                     [numeric](19, 2)        NULL,
    [res_per_real]                [numeric](19, 2)        NULL,
    [luc_disp]                    [numeric](19, 2)        NULL,
    [luc_disp_real]               [numeric](19, 2)        NULL,
    [res_neg_util]                [numeric](19, 2)        NULL,
    [res_neg_util_real]           [numeric](19, 2)        NULL,
    [saldo_res_neg_nao_util]      [numeric](19, 2)        NULL,
    [saldo_res_neg_nao_util_real] [numeric](19, 2)        NULL,
    [res_prop]                    [numeric](19, 2)        NULL,
    [res_prop_real]               [numeric](19, 2)        NULL,
    [res_neg]                     [numeric](19, 2)        NULL,
    [res_neg_real]                [numeric](19, 2)        NULL,
    [saldo_res_neg]               [numeric](19, 2)        NULL,
    [rend_pass_prop]              [numeric](19, 2)        NULL,
    [rend_pass_prop_real]         [numeric](19, 2)        NULL,
    [rend_total]                  [numeric](19, 2)        NULL,
    [rend_total_real]             [numeric](19, 2)        NULL,
    [rend_ativ_prop]              [numeric](19, 2)        NULL,
    [rend_ativ_prop_real]         [numeric](19, 2)        NULL,
    [perc_rend]                   [numeric](9, 4)         NULL,
    [perc_part]                   [numeric](9, 4)         NULL,
    [ativo_total]                 [numeric](19, 2)        NULL,
    [pat_liquido]                 [numeric](19, 2)        NULL,
    [processo_id]                 [varchar](44)           NULL,
    [log_usuid]                   [varchar](60)           NULL,
    [log_dt]                      [varchar](8)            NULL,
    [log_hr]                      [varchar](8)            NULL,
    [log_meio]                    [varchar](3)            NULL,
    [log_layout]                  [varchar](200)          NULL,
    [log_arqentrada]              [varchar](2000)         NULL,
    [reg]                         [varchar](100)          NULL,
    [per_ref]                     [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_infoecon_rendrecpag]
(
    [ecfierendrp_idseq]         [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [ind_rend]                  [char](1)               NULL,
    [dt_lcto]                   [varchar](8)            NULL,
    [pais]                      [varchar](3)            NULL,
    [vl_serv_assist]            [numeric](3, 0)         NULL,
    [vl_serv_sem_assist]        [numeric](19, 2)        NULL,
    [vl_serv_sem_assist_ext]    [numeric](19, 2)        NULL,
    [vl_juros_rec]              [numeric](19, 2)        NULL,
    [vl_juros_pf_pag]           [numeric](19, 2)        NULL,
    [vl_juros_pj_pag]           [numeric](19, 2)        NULL,
    [vl_demais_juros]           [numeric](19, 2)        NULL,
    [vl_divid_rec]              [numeric](19, 2)        NULL,
    [vl_divid_pf_pag]           [numeric](19, 2)        NULL,
    [vl_divid_pj_pag]           [numeric](19, 2)        NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_infoecon_royalties]
(
    [ecfieroy_idseq]            [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [tip_roy]                   [char](1)               NULL,
    [pais]                      [varchar](3)            NULL,
    [vl_expl_dir_sw]            [numeric](19, 2)        NULL,
    [vl_expl_dir_aut]           [numeric](19, 2)        NULL,
    [vl_expl_marca]             [numeric](19, 2)        NULL,
    [vl_expl_pat]               [numeric](19, 2)        NULL,
    [vl_expl_know]              [numeric](19, 2)        NULL,
    [vl_expl_franq]             [numeric](19, 2)        NULL,
    [vl_expl_int]               [numeric](19, 2)        NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_infogeral_ativosext]
(
    [ecfigaext_idseq]           [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [tip_ativo]                 [varchar](14)           NULL,
    [pais]                      [varchar](3)            NULL,
    [discriminacao]             [varchar](2000)         NULL,
    [vl_ant]                    [numeric](19, 2)        NULL,
    [vl_atual]                  [numeric](19, 2)        NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_infogeral_consorcios]
(
    [ecfigcons_idseq]           [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [cnpj_cons]                 [varchar](14)           NULL,
    [cond_decl]                 [numeric](1, 0)         NULL,
    [vl_cons]                   [numeric](19, 2)        NULL,
    [cnpj_lider]                [varchar](14)           NULL,
    [vl_decl]                   [numeric](19, 2)        NULL,
    [cnpj_part]                 [varchar](14)           NULL,
    [vl_part]                   [numeric](19, 2)        NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_infogeral_fundos]
(
    [ecfigfundo_idseq]          [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [cnpj]                      [varchar](14)           NULL,
    [qte_quot]                  [numeric](9, 0)         NULL,
    [qte_quota]                 [numeric](11, 0)        NULL,
    [patr_fin_per]              [numeric](19, 2)        NULL,
    [dt_abert]                  [varchar](8)            NULL,
    [dt_encer]                  [varchar](8)            NULL,
    [cond_decl]                 [numeric](1, 0)         NULL,
    [vl_cons]                   [numeric](19, 2)        NULL,
    [cnpj_lider]                [varchar](14)           NULL,
    [vl_decl]                   [numeric](19, 2)        NULL,
    [vl_part]                   [numeric](19, 2)        NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_infogeral_outrasinf]
(
    [ecfigoutinf_idseq]         [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [tipo_doc]                  [varchar](3)            NULL,
    [descricao]                 [varchar](2000)         NULL,
    [arq_hash]                  [varchar](41)           NULL,
    [arq_rtf]                   [text]                  NULL,
    [ind_fim_rtf]               [char](7)               NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_infogeral_outrasinflpa]
(
    [ecfigoinflpa_idseq]        [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [vl_capital_ant]            [numeric](19, 2)        NULL,
    [vl_capital]                [numeric](19, 2)        NULL,
    [vl_estoque_ant]            [numeric](19, 2)        NULL,
    [vl_estoques]               [numeric](19, 2)        NULL,
    [vl_caixa_ant]              [numeric](19, 2)        NULL,
    [vl_caixa]                  [numeric](19, 2)        NULL,
    [vl_aplic_fin_ant]          [numeric](19, 2)        NULL,
    [vl_aplic_fin]              [numeric](19, 2)        NULL,
    [vl_cta_rec_ant]            [numeric](19, 2)        NULL,
    [vl_cta_rec]                [numeric](19, 2)        NULL,
    [vl_cta_pag_ant]            [numeric](19, 2)        NULL,
    [vl_cta_pag]                [numeric](19, 2)        NULL,
    [vl_compra_merc]            [numeric](19, 2)        NULL,
    [vl_compra_ativo]           [numeric](19, 2)        NULL,
    [vl_receitas]               [numeric](19, 2)        NULL,
    [vl_tot_ativo]              [numeric](19, 2)        NULL,
    [vl_folha_pagto]            [numeric](19, 2)        NULL,
    [aliq_reduz]                [numeric](9, 4)         NULL,
    [ind_regime_apurrec]        [char](1)               NULL,
    [ind_aval_estoq]            [char](1)               NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_infogeral_pagrecext]
(
    [ecfigpagrec_idseq]         [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [ind_pagrec]                [char](1)               NULL,
    [dt_lcto]                   [varchar](8)            NULL,
    [pais]                      [varchar](3)            NULL,
    [forma]                     [char](1)               NULL,
    [nat_oper]                  [varchar](5)            NULL,
    [vl_periodo]                [numeric](19, 2)        NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_infogeral_particmep]
(
    [ecfigprtep_idseq]          [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [dt_evento]                 [varchar](8)            NULL,
    [ind_relac]                 [char](1)               NULL,
    [pais]                      [varchar](3)            NULL,
    [cnpj]                      [varchar](14)           NULL,
    [nom_emp]                   [varchar](2000)         NULL,
    [valor_reais]               [numeric](19, 2)        NULL,
    [valor_estr]                [numeric](19, 2)        NULL,
    [perc_cap_tot]              [numeric](8, 4)         NULL,
    [perc_cap_vot]              [numeric](8, 4)         NULL,
    [res_eq_pat]                [numeric](19, 2)        NULL,
    [data_aquis]                [varchar](8)            NULL,
    [ind_proc_cart]             [char](1)               NULL,
    [num_proc_cart]             [varchar](2000)         NULL,
    [nome_cart]                 [varchar](2000)         NULL,
    [ind_proc_rfb]              [char](1)               NULL,
    [num_proc_rfb]              [varchar](2000)         NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_infogeral_perant]
(
    [ecfigpant_idseq]           [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [luc_liq]                   [numeric](19, 2)        NULL,
    [dt_luc_liq]                [varchar](8)            NULL,
    [rec_brut_ant]              [numeric](19, 2)        NULL,
    [intimacao]                 [char](1)               NULL,
    [int_atraso]                [char](1)               NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_infogeral_refis]
(
    [ecfigrefis_idseq]          [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [mes]                       [char](2)               NULL,
    [acres_patr]                [numeric](19, 2)        NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_infogeral_socios]
(
    [ecfigsocio_idseq]          [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [dt_alt_soc]                [varchar](8)            NULL,
    [dt_fim_soc]                [varchar](8)            NULL,
    [pais]                      [varchar](3)            NULL,
    [ind_qualif]                [char](2)               NULL,
    [cpf_cnpj]                  [varchar](14)           NULL,
    [nom_emp]                   [varchar](2000)         NULL,
    [qualif]                    [char](2)               NULL,
    [perc_cap_tot]              [numeric](8, 4)         NULL,
    [perc_cap_vot]              [numeric](8, 4)         NULL,
    [cpf_rep_leg]               [numeric](11, 0)        NULL,
    [qualif_rep_leg]            [numeric](2, 0)         NULL,
    [vl_rem_trab]               [numeric](19, 2)        NULL,
    [vl_luc_div]                [numeric](19, 2)        NULL,
    [vl_jur_cap]                [numeric](19, 2)        NULL,
    [vl_dem_rend]               [numeric](19, 2)        NULL,
    [vl_ir_ret]                 [numeric](19, 2)        NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_infogeral_sucessoras]
(
    [ecfigsuc_idseq]            [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [cnpj_suc]                  [varchar](14)           NULL,
    [nom_emp]                   [varchar](2000)         NULL,
    [perc_pat_liq]              [numeric](9, 4)         NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_infogeral_tributosrf]
(
    [ecfigtribrf_idseq]         [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [cnpj_fon]                  [varchar](14)           NULL,
    [cod_rec]                   [varchar](4)            NULL,
    [nom_emp]                   [varchar](2000)         NULL,
    [ind_org_pub]               [char](1)               NULL,
    [vl_rend]                   [numeric](19, 2)        NULL,
    [ir_ret]                    [numeric](19, 2)        NULL,
    [csll_ret]                  [numeric](19, 2)        NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_justificativas]
(
    [ecfjust_idseq]             [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [tipo_justificativa]        [varchar](60)           NULL,
    [per_apur]                  [char](3)               NULL,
    [cod_cta]                   [varchar](60)           NULL,
    [cod_ccus]                  [varchar](60)           NULL,
    [justificativa]             [varchar](500)          NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_lalura_lancamentos]
(
    [ecflasld_idseq]            [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [per_apur]                  [char](3)               NULL,
    [cod_tributo]               [char](1)               NULL,
    [cod_linha]                 [varchar](60)           NULL,
    [cod_linha_n]               [numeric](9, 4)         NULL,
    [tipo_lancamento]           [char](1)               NULL,
    [ind_relacao]               [numeric](1, 0)         NULL,
    [valor]                     [numeric](19, 2)        NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_lalura_linhas]
(
    [ecflalin_idseq]            [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [cod_tributo]               [char](1)               NULL,
    [cod_linha]                 [varchar](60)           NULL,
    [ind_relacao]               [char](1)               NULL,
    [cod_cta]                   [varchar](60)           NULL,
    [cod_ccus]                  [varchar](60)           NULL,
    [num_lcto]                  [varchar](50)           NULL,
    [tipo_lancamento]           [char](1)               NULL,
    [hist_lan_lal]              [varchar](500)          NULL,
    [ind_proc]                  [char](1)               NULL,
    [num_proc]                  [varchar](20)           NULL,
    [validade_dtini]            [varchar](8)            NULL,
    [validade_dtfin]            [varchar](8)            NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_lalurb_contas]
(
    [ecflbcta_idseq]            [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [cod_tributo]               [char](1)               NULL,
    [cod_cta]                   [varchar](60)           NULL,
    [desc_cta_lal]              [varchar](2000)         NULL,
    [cod_cta_ctp]               [varchar](60)           NULL,
    [dt_ap_lal]                 [varchar](8)            NULL,
    [cod_pb_rfb]                [varchar](60)           NULL,
    [dt_lim_lal]                [varchar](8)            NULL,
    [vl_sld_ini]                [numeric](19, 2)        NULL,
    [ind_dc_ini]                [char](1)               NULL,
    [cnpj_sit_esp]              [numeric](14, 0)        NULL,
    [ind_proc]                  [char](1)               NULL,
    [num_proc]                  [varchar](20)           NULL,
    [validade_dtini]            [varchar](8)            NULL,
    [validade_dtfin]            [varchar](8)            NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_lalurb_lancamentos]
(
    [ecflblct_idseq]            [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [per_apur]                  [char](3)               NULL,
    [cod_tributo]               [char](1)               NULL,
    [dt_lcto]                   [varchar](8)            NULL,
    [num_lcto]                  [varchar](60)           NULL,
    [cod_cta]                   [varchar](60)           NULL,
    [cod_cta_ctp]               [varchar](60)           NULL,
    [ind_origem]                [varchar](2)            NULL,
    [vl_dc_lcto]                [numeric](19, 2)        NULL,
    [ind_vl_lcto]               [char](2)               NULL,
    [hist]                      [varchar](2000)         NULL,
    [ind_lan_ant]               [char](1)               NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_lalurb_saldos]
(
    [ecflbsld_idseq]            [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [per_apur]                  [char](3)               NULL,
    [cod_tributo]               [char](1)               NULL,
    [cod_cta]                   [varchar](60)           NULL,
    [vl_sld_ini]                [numeric](19, 2)        NULL,
    [ind_dc_ini]                [char](1)               NULL,
    [vl_deb]                    [numeric](19, 2)        NULL,
    [vl_cred]                   [numeric](19, 2)        NULL,
    [vl_sld_fin]                [numeric](19, 2)        NULL,
    [ind_dc_fin]                [char](1)               NULL,
    [cnpj_sit_esp]              [numeric](14, 0)        NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_registro_valores]
(
    [ecfregvl_idseq]            [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [per_apur]                  [char](3)               NULL,
    [cod_reg]                   [varchar](4)            NULL,
    [codigo]                    [varchar](60)           NULL,
    [descricao]                 [varchar](2000)         NULL,
    [valor]                     [numeric](19, 2)        NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[ecf_saldo_contasref]
(
    [ecfsldref_idseq]           [bigint] IDENTITY (1,1) NOT NULL,
    [id_pai]                    [varchar](60)           NULL,
    [id]                        [varchar](180)          NULL,
    [estabelecimento_matriz_id] [varchar](60)           NULL,
    [periodo_dtini]             [varchar](8)            NULL,
    [periodo_dtfin]             [varchar](8)            NULL,
    [cod_cta]                   [varchar](60)           NULL,
    [cod_ccus]                  [varchar](60)           NULL,
    [cod_cta_ref]               [varchar](60)           NULL,
    [vl_sld_ini]                [numeric](19, 2)        NULL,
    [ind_dc_ini]                [char](1)               NULL,
    [vl_deb]                    [numeric](19, 2)        NULL,
    [vl_cred]                   [numeric](19, 2)        NULL,
    [vl_sld_fin]                [numeric](19, 2)        NULL,
    [ind_dc_fin]                [char](1)               NULL,
    [processo_id]               [varchar](44)           NULL,
    [log_usuid]                 [varchar](60)           NULL,
    [log_dt]                    [varchar](8)            NULL,
    [log_hr]                    [varchar](8)            NULL,
    [log_meio]                  [varchar](3)            NULL,
    [log_layout]                [varchar](200)          NULL,
    [log_arqentrada]            [varchar](2000)         NULL,
    [reg]                       [varchar](100)          NULL,
    [per_ref]                   [varchar](8)            NULL
) ON [PRIMARY]
GO
/* Tabelas apenas para teste */
CREATE TABLE [dbo].[temp_0150_0180]
(
    ID_0150     VARCHAR(20),
    ID_PAI_0150 VARCHAR(10),
    ID_0180     VARCHAR(30),
    COD_PART    VARCHAR(10),
    NOME        VARCHAR(50),
    COD_PAIS    VARCHAR(5),
    CNPJ        VARCHAR(14),
    CPF         VARCHAR(11),
    NIT         VARCHAR(20),
    UF          VARCHAR(2),
    IE          VARCHAR(20),
    IE_ST       VARCHAR(20),
    COD_MUN     VARCHAR(10),
    IM          VARCHAR(20),
    SUFRAMA     VARCHAR(20),
    COD_REL     VARCHAR(10),
    DT_INI_REL  VARCHAR(10),
    DT_FIN_REL  VARCHAR(10)
) ON [PRIMARY]
GO