version: '3.7'
services:
  sql-server:
    image:  docker.io/library/sqlserver-geracao-ecf:default
    container_name: sql-server
    environment:
      - MSSQL_SA_PASSWORD=Password@123
      - ACCEPT_EULA=Y
    ports:
      - '1433:1433'