version: '3.7'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      - MSSQL_SA_PASSWORD=Password@123
      - ACCEPT_EULA=Y
    ports:
      - '1433:1433'